db:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root
    database: userdb
    table: usertable
    userfield: username
    passfield: password
    algorithm: SHA-512
string:
    join: This server is running exAuth. Use /login PASSWORD to log in.
    login_missing_parameter: You must specify a password, usage is /login PASSWORD